Skip to content
Search or jump to…

Pull requests
Issues
Marketplace
Explore
 
@ossdev07 
0
091ossdev07/constructor
forked from conda/constructor
 Code Pull requests 0 Actions Projects 0 Wiki Security Insights Settings
constructor/.travis.yml
@msarahan msarahan remove support for conda less than 4.6
44d73bd on Aug 9, 2019
@msarahan@nehaljwani@soapy1@goanpeca
82 lines (70 sloc)  2.06 KB
  
# https://travis-ci.org/conda/constructor

language: python
sudo: false

branches:
  only:
    - master

env:
  global:
    - CONSTRUCTOR_CACHE=/tmp/constructor_travis_ci

matrix:
  include:
    # Linux
    - os: linux
      language: generic
      env: PYTHON_VERSION=3.6 CONDA_VERSION=4.6
    - os: linux
      language: generic
      env: PYTHON_VERSION=2.7 CONDA_CANARY=true
    - os: linux
      language: generic
      env: PYTHON_VERSION=3.7 CONDA_CANARY=true
    # OSX
    - os: osx
      language: generic
      env: PYTHON_VERSION=3.6 CONDA_VERSION=4.7
  allow_failures:
    - os: linux
      language: generic
      env: PYTHON_VERSION=3.7 CONDA_CANARY=true
    - os: linux
      language: generic
      env: PYTHON_VERSION=2.7 CONDA_CANARY=true

cache:
  directories:
    - $HOME/condacache/pkgs
    - $HOME/.cache/pip

install:
  - mkdir -p $HOME/condacache/pkgs
  # Install latest miniconda
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      wget https://repo.anaconda.com/pkgs/misc/conda-execs/conda-latest-linux-64.exe -O conda.exe;
    else
      wget https://repo.anaconda.com/pkgs/misc/conda-execs/conda-latest-osx-64.exe -O conda.exe;
    fi
  - chmod +x conda.exe

  - export CONDA_PKGS_DIRS="~/condacache/pkgs"
  - export CONDA_ALWAYS_YES="true"
  - export CONDA_AUTO_UPDATE_CONDA="false"

  - if [ "${CONDA_CANARY}" = "true" ]; then
      ./conda.exe config --add channels conda-canary;
      ./conda.exe update conda.exe;
      ./conda.exe create -y -q -n test conda python=3.7;
    else
      ./conda.exe create -y -q -p ~/miniconda -c conda-canary conda=$CONDA_VERSION python=$PYTHON_VERSION;
    fi
  - ./conda.exe install -n test pillow>=3.1 ruamel_yaml conda-forge::codecov pytest pytest-cov
  - source "$HOME"/miniconda/bin/activate test 
  # Install this package
  - pip install --user .

  # this needs
  - mkdir $HOME/miniconda/standalone_conda
  - cp conda.exe $HOME/miniconda/standalone_conda/conda.exe

  # diagnostics
  - conda info
  - conda init
  - source "$HOME"/miniconda/bin/activate
  - conda list

script:
  - pytest --cov=constructor constructor
  - python scripts/run_examples.py

after_success:
  - codecov
© 2020 GitHub, Inc.
Terms
Privacy
Security
Status
Help
Contact GitHub
Pricing
API
Training
Blog
About
